language: go

sudo: required

matrix:
  include:
    - go: 1.10.1

sxript:
  - ./hack/scripts/go.sh
  - ./hack/scripts/protoc.sh
  - make tools
  - make check
  - make compile
  - make test
  - make test-e2e
  - make cover
