language: go

sudo: required

services:
  - postgresql
  - mysql


matrix:
  include:
    - go: 1.12.8

before_script:
  - ./hack/scripts/install_tools.sh
  - ./hack/scripts/install_protoc.sh
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'


script:
  - make check
  - make compile
  - make test
  - make test-e2e
  - make cover
