language: go

sudo: required

matrix:
  include:
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x

install:
  - ./hack/scripts/go.sh
  - ./hack/scripts/protoc.sh
  - make tools

script:
  - make check
  - make install
  - make test
  - make test-e2e
  - make cover
