language: go

sudo: required

matrix:
  include:
    - go: 1.10.1

before_script:
  - ./hack/scripts/go.sh
  - ./hack/scripts/protoc.sh
  - make tools

script:
  - make check
  - make compile
  - make test
  - make cover
