language: go

sudo: required

services:
  - docker

matrix:
  include:
    - go: 1.10.1

before_script:
  - ./hack/scripts/go.sh
  - ./hack/scripts/protoc.sh
  - make tools
  - docker --version

script:
  - make check
  - make compile
  - make test
  - make test-e2e
  - make cover

