// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: protoc-gen-orm/testdata/message_options.proto

package ormpb_example

func (*Example) TableName() string {
	return "examples"
}

func (*Example) Tag(field, tag string) (val string, found bool) {
	m := map[string]map[string]string{

		"Label": {
			"name": "labels",
			"type": "blob",
		},

		"Type": {
			"type": "bigint",
		},
	}
	val, found = m[field][tag]
	return
}
