// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: protoc-gen-orm/testdata/message_options.proto

package ormpb_example

const (
	ColumnTagName          = "Name"
	ColumnTagType          = "Type"
	ColumnTagSize          = "Size"
	ColumnTagPrimaryKey    = "PrimaryKey"
	ColumnTagUnique        = "Unique"
	ColumnTagDefault       = "Default"
	ColumnTagNotNull       = "NotNull"
	ColumnTagAutoIncrement = "AutoIncrement"
)

func (*Example) TableName() string {
	return "examples"
}

func (*Example) Tag(field, tag string) (val string, found bool) {
	m := map[string]map[string]string{
		"Label": {
			ColumnTagAutoIncrement: "false",
			ColumnTagName:          "labels",
			ColumnTagNotNull:       "false",
			ColumnTagPrimaryKey:    "false",
			ColumnTagSize:          "0",
			ColumnTagType:          "blob",
			ColumnTagUnique:        "false",
		},
		"Type": {
			ColumnTagAutoIncrement: "false",
			ColumnTagNotNull:       "false",
			ColumnTagPrimaryKey:    "false",
			ColumnTagSize:          "0",
			ColumnTagType:          "bigint",
			ColumnTagUnique:        "false",
		},
	}
	val, found = m[field][tag]
	return
}
