// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: protoc-gen-orm/testdata/message_options.proto

package ormpb_example

func (*Example) TableName() string {
	return "examples"
}

func (*Example) Tag(field, name string) map[string]map[string]string {
	m := map[string]map[string]string{

		"Label": map[string]string{
			"name": "labels",
			"type": "blob",
		},

		"Type": map[string]string{
			"type": "bigint",
		},
	}
	return m
}
