
/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: ormpb/examples/import/example.proto
*/


/* Generated for Example */
DROP TABLE IF EXISTS examples;


/* Generated for ExampleAutoIncrement */
DROP TABLE IF EXISTS example_auto_increment;
