// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/option.proto

/*
Package ormpb_protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/option.proto

It has these top-level messages:
	TableOptions
	ColumnOptions
*/
package ormpb_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TableOptions struct {
	// table_name specifies the table name for the message
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TableOptions) Reset()                    { *m = TableOptions{} }
func (m *TableOptions) String() string            { return proto.CompactTextString(m) }
func (*TableOptions) ProtoMessage()               {}
func (*TableOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TableOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ColumnOptions struct {
	// column_name specifies column name
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// type specifies column data type
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// size specifies column size, default 255
	Size int32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// primary_key specifies column as primary key
	PrimaryKey bool `protobuf:"varint,4,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	// unique specifies column as unique
	Unique bool `protobuf:"varint,5,opt,name=unique" json:"unique,omitempty"`
	// default specifies column default value
	Default string `protobuf:"bytes,6,opt,name=default" json:"default,omitempty"`
	// not_null specifies column as NOT NULL
	NotNull bool `protobuf:"varint,7,opt,name=not_null,json=notNull" json:"not_null,omitempty"`
	// auto_increment specifies column auto incrementable or not
	AutoIncrement bool `protobuf:"varint,8,opt,name=auto_increment,json=autoIncrement" json:"auto_increment,omitempty"`
}

func (m *ColumnOptions) Reset()                    { *m = ColumnOptions{} }
func (m *ColumnOptions) String() string            { return proto.CompactTextString(m) }
func (*ColumnOptions) ProtoMessage()               {}
func (*ColumnOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ColumnOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnOptions) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ColumnOptions) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ColumnOptions) GetPrimaryKey() bool {
	if m != nil {
		return m.PrimaryKey
	}
	return false
}

func (m *ColumnOptions) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *ColumnOptions) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *ColumnOptions) GetNotNull() bool {
	if m != nil {
		return m.NotNull
	}
	return false
}

func (m *ColumnOptions) GetAutoIncrement() bool {
	if m != nil {
		return m.AutoIncrement
	}
	return false
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*TableOptions)(nil),
	Field:         10000001,
	Name:          "ormpb.protobuf.table",
	Tag:           "bytes,10000001,opt,name=table",
	Filename:      "protobuf/option.proto",
}

var E_Column = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*ColumnOptions)(nil),
	Field:         10000003,
	Name:          "ormpb.protobuf.column",
	Tag:           "bytes,10000003,opt,name=column",
	Filename:      "protobuf/option.proto",
}

func init() {
	proto.RegisterType((*TableOptions)(nil), "ormpb.protobuf.TableOptions")
	proto.RegisterType((*ColumnOptions)(nil), "ormpb.protobuf.ColumnOptions")
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Column)
}

func init() { proto.RegisterFile("protobuf/option.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xc9, 0xf7, 0xb5, 0x69, 0x9d, 0xda, 0x1e, 0x16, 0x94, 0x55, 0x2c, 0x0d, 0x05, 0xa1,
	0xa7, 0x14, 0xf4, 0xd6, 0xab, 0x20, 0x88, 0xa8, 0x10, 0x44, 0x8f, 0x25, 0x69, 0xa7, 0x65, 0x71,
	0xb3, 0x13, 0x37, 0xbb, 0x87, 0x78, 0x13, 0x7f, 0x8f, 0xff, 0x49, 0xfc, 0x25, 0x92, 0x4d, 0xb7,
	0x58, 0x05, 0x6f, 0x33, 0xef, 0xbc, 0x79, 0xb2, 0x3c, 0x70, 0x50, 0x68, 0x32, 0x94, 0xd9, 0xd5,
	0x94, 0x0a, 0x23, 0x48, 0xc5, 0x6e, 0x67, 0x03, 0xd2, 0x79, 0x91, 0xc5, 0xfe, 0x78, 0x1c, 0xad,
	0x89, 0xd6, 0x12, 0xa7, 0xdb, 0xf6, 0x12, 0xcb, 0x85, 0x16, 0x85, 0x21, 0xdd, 0x94, 0xc6, 0x63,
	0xd8, 0xbf, 0x4f, 0x33, 0x89, 0x77, 0x0e, 0x53, 0x32, 0x06, 0x2d, 0x95, 0xe6, 0xc8, 0x83, 0x28,
	0x98, 0xec, 0x25, 0x6e, 0x1e, 0x7f, 0x04, 0xd0, 0xbf, 0x20, 0x69, 0x73, 0xf5, 0x47, 0xab, 0xce,
	0x4c, 0x55, 0x20, 0xff, 0xd7, 0x64, 0xf5, 0x5c, 0x67, 0xa5, 0x78, 0x41, 0xfe, 0x3f, 0x0a, 0x26,
	0xed, 0xc4, 0xcd, 0x6c, 0x04, 0xbd, 0x42, 0x8b, 0x3c, 0xd5, 0xd5, 0xfc, 0x09, 0x2b, 0xde, 0x8a,
	0x82, 0x49, 0x37, 0x81, 0x4d, 0x74, 0x8d, 0x15, 0x3b, 0x84, 0xd0, 0x2a, 0xf1, 0x6c, 0x91, 0xb7,
	0xdd, 0x6d, 0xb3, 0x31, 0x0e, 0x9d, 0x25, 0xae, 0x52, 0x2b, 0x0d, 0x0f, 0xdd, 0x3f, 0xfc, 0xca,
	0x8e, 0xa0, 0xab, 0xc8, 0xcc, 0x95, 0x95, 0x92, 0x77, 0xdc, 0x37, 0x1d, 0x45, 0xe6, 0xd6, 0x4a,
	0xc9, 0x4e, 0x61, 0x90, 0x5a, 0x43, 0x73, 0xa1, 0x16, 0x1a, 0x73, 0x54, 0x86, 0x77, 0x5d, 0xa1,
	0x5f, 0xa7, 0x57, 0x3e, 0x9c, 0x3d, 0x40, 0xdb, 0xd4, 0x1a, 0xd8, 0x28, 0x6e, 0x94, 0x6d, 0x1d,
	0xc6, 0x37, 0x58, 0x96, 0xe9, 0xda, 0x0b, 0xe2, 0xaf, 0xef, 0x9f, 0xf5, 0x93, 0x7b, 0x67, 0x27,
	0xf1, 0xae, 0xec, 0xf8, 0xbb, 0xc7, 0xa4, 0xc1, 0xcd, 0x1e, 0x21, 0x5c, 0x38, 0x73, 0x6c, 0xf8,
	0x0b, 0x7c, 0x29, 0x50, 0x2e, 0x3d, 0xf6, 0xcd, 0x63, 0x87, 0x3f, 0xb1, 0x3b, 0xe6, 0x93, 0x0d,
	0x2e, 0x0b, 0xdd, 0xfd, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x92, 0xea, 0x96, 0x09, 0x02,
	0x00, 0x00,
}
