// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/option.proto

/*
Package ormpb_protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf/option.proto

It has these top-level messages:
	TableOptions
	ColumnOptions
*/
package ormpb_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TableOptions struct {
	// table_name specifies the table name for the message
	Name                         *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *TableOptions) Reset()                    { *m = TableOptions{} }
func (m *TableOptions) String() string            { return proto.CompactTextString(m) }
func (*TableOptions) ProtoMessage()               {}
func (*TableOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

var extRange_TableOptions = []proto.ExtensionRange{
	{10000001, 10000003},
}

func (*TableOptions) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_TableOptions
}

func (m *TableOptions) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ColumnOptions struct {
	// column_name specifies column name
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// type specifies column data type
	Type *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// size specifies column size, default 255
	Size *int32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// primary_key specifies column as primary key
	PrimaryKey *bool `protobuf:"varint,4,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	// unique specifies column as unique
	Unique *bool `protobuf:"varint,5,opt,name=unique" json:"unique,omitempty"`
	// default specifies column default value
	Default *string `protobuf:"bytes,6,opt,name=default" json:"default,omitempty"`
	// not_null specifies column as NOT NULL
	NotNull *bool `protobuf:"varint,7,opt,name=not_null,json=notNull" json:"not_null,omitempty"`
	// auto_increment specifies column auto incrementable or not
	AutoIncrement    *bool  `protobuf:"varint,8,opt,name=auto_increment,json=autoIncrement" json:"auto_increment,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ColumnOptions) Reset()                    { *m = ColumnOptions{} }
func (m *ColumnOptions) String() string            { return proto.CompactTextString(m) }
func (*ColumnOptions) ProtoMessage()               {}
func (*ColumnOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ColumnOptions) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnOptions) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ColumnOptions) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ColumnOptions) GetPrimaryKey() bool {
	if m != nil && m.PrimaryKey != nil {
		return *m.PrimaryKey
	}
	return false
}

func (m *ColumnOptions) GetUnique() bool {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return false
}

func (m *ColumnOptions) GetDefault() string {
	if m != nil && m.Default != nil {
		return *m.Default
	}
	return ""
}

func (m *ColumnOptions) GetNotNull() bool {
	if m != nil && m.NotNull != nil {
		return *m.NotNull
	}
	return false
}

func (m *ColumnOptions) GetAutoIncrement() bool {
	if m != nil && m.AutoIncrement != nil {
		return *m.AutoIncrement
	}
	return false
}

var E_Table = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*TableOptions)(nil),
	Field:         10000001,
	Name:          "ormpb.protobuf.table",
	Tag:           "bytes,10000001,opt,name=table",
	Filename:      "protobuf/option.proto",
}

var E_Column = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*ColumnOptions)(nil),
	Field:         10000003,
	Name:          "ormpb.protobuf.column",
	Tag:           "bytes,10000003,opt,name=column",
	Filename:      "protobuf/option.proto",
}

func init() {
	proto.RegisterType((*TableOptions)(nil), "ormpb.protobuf.TableOptions")
	proto.RegisterType((*ColumnOptions)(nil), "ormpb.protobuf.ColumnOptions")
	proto.RegisterExtension(E_Table)
	proto.RegisterExtension(E_Column)
}

func init() { proto.RegisterFile("protobuf/option.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xbf, 0x7e, 0x76, 0x5b, 0x3d, 0x73, 0x43, 0x02, 0x4a, 0x14, 0xc7, 0xca, 0x40, 0x28,
	0x5e, 0x74, 0xe2, 0xe5, 0x6e, 0x05, 0x41, 0x44, 0x85, 0x22, 0x7a, 0x39, 0xba, 0xed, 0x6c, 0x04,
	0xd3, 0xa4, 0xa6, 0xc9, 0x45, 0xbd, 0x13, 0xfd, 0x3b, 0xfb, 0x4f, 0xb2, 0x5f, 0x22, 0x4d, 0x97,
	0xe1, 0x14, 0xbc, 0x3b, 0xe7, 0xcd, 0x7b, 0x9e, 0xc0, 0x03, 0x07, 0xb9, 0x92, 0x5a, 0x4e, 0xcc,
	0x7c, 0x28, 0x73, 0xcd, 0xa4, 0x88, 0xed, 0x4e, 0xba, 0x52, 0x65, 0xf9, 0x24, 0x76, 0x8f, 0xc7,
	0xe1, 0x42, 0xca, 0x05, 0xc7, 0xe1, 0xa6, 0x3d, 0xc3, 0x62, 0xaa, 0x58, 0xae, 0xa5, 0xaa, 0x4b,
	0x83, 0x73, 0xd8, 0x7b, 0x48, 0x27, 0x1c, 0xef, 0x2d, 0xa6, 0x20, 0x04, 0x7c, 0x91, 0x66, 0x48,
	0xbd, 0xd0, 0x8b, 0x76, 0x13, 0x3b, 0x9f, 0x41, 0xf0, 0xb6, 0x5c, 0xf9, 0xfb, 0x1f, 0xcb, 0x95,
	0x9f, 0xfc, 0x1b, 0x7c, 0x7a, 0xd0, 0xb9, 0x94, 0xdc, 0x64, 0xe2, 0x8f, 0x9b, 0x2a, 0xd3, 0x65,
	0x8e, 0xf4, 0x7f, 0x9d, 0x55, 0x73, 0x95, 0x15, 0xec, 0x15, 0xe9, 0x4e, 0xe8, 0x45, 0x8d, 0xc4,
	0xce, 0xa4, 0x0f, 0xed, 0x5c, 0xb1, 0x2c, 0x55, 0xe5, 0xf8, 0x19, 0x4b, 0xea, 0x87, 0x5e, 0x14,
	0x24, 0xb0, 0x8e, 0x6e, 0xb0, 0x24, 0x87, 0xd0, 0x34, 0x82, 0xbd, 0x18, 0xa4, 0x0d, 0xfb, 0xb6,
	0xde, 0x08, 0x85, 0xd6, 0x0c, 0xe7, 0xa9, 0xe1, 0x9a, 0x36, 0xed, 0x1f, 0x6e, 0x25, 0x47, 0x10,
	0x08, 0xa9, 0xc7, 0xc2, 0x70, 0x4e, 0x5b, 0xf6, 0xa6, 0x25, 0xa4, 0xbe, 0x33, 0x9c, 0x93, 0x53,
	0xe8, 0xa6, 0x46, 0xcb, 0x31, 0x13, 0x53, 0x85, 0x19, 0x0a, 0x4d, 0x03, 0x5b, 0xe8, 0x54, 0xe9,
	0xb5, 0x0b, 0x47, 0x8f, 0xd0, 0xd0, 0x95, 0x14, 0xd2, 0x8f, 0x6b, 0x81, 0x1b, 0xa3, 0xf1, 0x2d,
	0x16, 0x45, 0xba, 0x70, 0xba, 0x68, 0x25, 0x26, 0xf4, 0xa2, 0xf6, 0xc5, 0x49, 0xbc, 0xad, 0x3e,
	0xfe, 0x6e, 0x35, 0xa9, 0x71, 0xa3, 0x27, 0x68, 0x4e, 0xad, 0x39, 0xd2, 0xfb, 0x05, 0xbe, 0x62,
	0xc8, 0x67, 0x0e, 0xfb, 0xee, 0xb0, 0xbd, 0x9f, 0xd8, 0x2d, 0xf3, 0xc9, 0x1a, 0xf7, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0x60, 0x08, 0x0c, 0x0f, 0x02, 0x00, 0x00,
}
