/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: ormpb/examples/mysql/example.proto
*/


/* Generated for ExampleAutoIncrement */
CREATE TABLE example_auto_increment (
	user_id INT AUTO_INCREMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
