/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: ormpb/examples/mysql/example.proto
*/


/* Generated for Example */
CREATE TABLE examples (
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128),
	email VARCHAR(256) NOT NULL UNIQUE,
	point DOUBLE DEFAULT 17.33,
	created_at TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
