/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: ormpb/examples/mysql/example.proto
*/


/* Generated for Example */
CREATE TABLE examples (
	user_id INT AUTO_INCREMENT,
	name VARCHAR(128) PRIMARY KEY,
	email LONGTEXT NOT NULL UNIQUE,
	point NUMERIC DEFAULT 17.33,
	created_at TIMESTAMP
);


/* Generated for ExampleAutoIncrement */
CREATE TABLE example_auto_increment (
	user_id SERIAL
);
