/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: ormpb/examples/postgres/example.proto
*/


/* Generated for ExampleAutoIncrement */
CREATE TABLE example_auto_increment (
	user_id SERIAL
);
