package orm

import (
	"bytes"
	"fmt"
	"reflect"
	"text/template"

	"github.com/gophersbd/ormpb/pkg/descriptor"
)

func printInterface(v interface{}) string {
	return fmt.Sprintf(`"%v"`, v)
}

var fns = template.FuncMap{
	"has_tag": func(a interface{}) bool {
		return reflect.ValueOf(a).Len() > 0
	},
}

type param struct {
	*descriptor.File
	Imports []descriptor.GoPackage
}

func applyTemplate(p param) (string, error) {
	w := bytes.NewBuffer(nil)

	helperTemplate := template.New("orm")
	helperTemplate.Funcs(template.FuncMap{"printInterface": printInterface})
	helperTemplate = helperTemplate.Funcs(fns)
	ormTemplate := template.Must(helperTemplate.Parse(ormTemplate))

	if err := ormTemplate.Execute(w, p); err != nil {
		return "", err
	}
	return w.String(), nil
}

var (
	ormTemplate = `
// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: {{ .GetName }}

package {{ .GoPkg.Name }}

import (
	{{range $i := .Imports}}
		{{if not $i.Standard}}
			{{ $i.Name }} "{{ $i.Path }}"
		{{end}}
	{{end}}
)

{{ range $msg := .Messages }}

func (*{{ $msg.Name }}) TableName() string {
	return "{{ $msg.TableOptions.GetName }}"
}

var (
	_{{ $msg.Name }}TagMap = map[string]map[string]string{
		{{- range $f := $msg.Fields }}
			{{- if has_tag $f.Column.Tags }}
				"{{- $f.Name }}": {
					{{- range $key, $value := $f.Column.Tags }}
						{{- if $value }}
							runtime.ColumnTag{{ $key }}: {{ $value | printInterface }},
						{{- end }}
					{{- end }}
				},
			{{- end }}
		{{- end }}
	}
)

func (*{{ $msg.Name }}) Tag(field, tag string) (val string, found bool) {
	val, found = _{{ $msg.Name }}TagMap[field][tag]
	return
}
{{- end }}
`
)
