// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: ormpb/examples/import/example.proto

package importpb

const (
	ColumnTagName          = "Name"
	ColumnTagType          = "Type"
	ColumnTagSize          = "Size"
	ColumnTagPrimaryKey    = "PrimaryKey"
	ColumnTagUnique        = "Unique"
	ColumnTagDefault       = "Default"
	ColumnTagNotNull       = "NotNull"
	ColumnTagAutoIncrement = "AutoIncrement"
)

func (*Example) TableName() string {
	return "examples"
}

var (
	_ExampleTagMap = map[string]map[string]string{
		"Name": {
			ColumnTagAutoIncrement: "false",
			ColumnTagName:          "name",
			ColumnTagNotNull:       "false",
			ColumnTagPrimaryKey:    "false",
			ColumnTagSize:          "0",
			ColumnTagUnique:        "false",
		},
	}
)

func (*Example) Tag(field, tag string) (val string, found bool) {
	val, found = _ExampleTagMap[field][tag]
	return
}
