// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: ormpb/examples/import/example.proto

package importpb

import (
	runtime "github.com/gophersbd/ormpb/pkg/runtime"
)

func (*Example) TableName() string {
	return "examples"
}

var (
	_ExampleTagMap = map[string]map[string]string{
		"UserId": {
			runtime.ColumnTagAutoIncrement: "true",
		},
		"Name": {
			runtime.ColumnTagName:       "name",
			runtime.ColumnTagPrimaryKey: "true",
			runtime.ColumnTagSize:       "128",
		},
		"Email": {
			runtime.ColumnTagNotNull: "true",
			runtime.ColumnTagUnique:  "true",
		},
		"Point": {
			runtime.ColumnTagDefault: "17.33",
		},
	}
)

func (*Example) Tag(field, tag string) (val string, found bool) {
	val, found = _ExampleTagMap[field][tag]
	return
}

func (*SecondExample) TableName() string {
	return "second_examples"
}

var (
	_SecondExampleTagMap = map[string]map[string]string{
		"UserId": {
			runtime.ColumnTagAutoIncrement: "true",
		},
	}
)

func (*SecondExample) Tag(field, tag string) (val string, found bool) {
	val, found = _SecondExampleTagMap[field][tag]
	return
}
