// Code generated by protoc-gen-orm. DO NOT EDIT.
// source: ormpb/examples/import/example.proto

package importpb

import (
	runtime "github.com/gophersbd/ormpb/pkg/runtime"
)

func (*Example) TableName() string {
	return "examples"
}

var (
	_ExampleTagMap = map[string]map[string]string{
		"Name": {
			runtime.ColumnTagName:       "name",
			runtime.ColumnTagPrimaryKey: "true",
			runtime.ColumnTagSize:       "128",
		},
	}
)

func (*Example) Tag(field, tag string) (val string, found bool) {
	val, found = _ExampleTagMap[field][tag]
	return
}
