package migration

import (
	"bytes"
	"text/template"

	"github.com/gophersbd/ormpb/pkg/descriptor"
)

func applyTemplateComment(file *descriptor.File) (string, error) {
	w := bytes.NewBuffer(nil)

	helperTemplate := template.New("comment")
	migrationCommentTemplate := template.Must(helperTemplate.Parse(migrationCommentTemplate))

	if err := migrationCommentTemplate.Execute(w, file); err != nil {
		return "", err
	}
	return w.String(), nil
}

var migrationCommentTemplate = `/*
	Migration file generated by protoc-gen-orm. DO NOT EDIT.
	source: {{ .GetName }}
*/
`
